title: "The Happy Lab"
description: "The Happy Lab is a human factors in computer security and privacy research group at Arizona State University."
url: "https://happyresearchlab.com"
baseurl: ""
google_analytics_id: "G-H08E251YST"

exclude:
  - README.md
  - LICENSE

markdown: kramdown
highlighter: rouge

nav:
  - name: "home"
    href: "/"
  - name: "publications"
    href: "/publication/"
  - name: "people"
    href: "/people/"
  - name: "Join the Lab!"
    href: "/apply/"

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "people"
      type: "pages"
    values:
      layout: "profile"
      person_page: true
