# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "The Happy Lab"
title:              "The Happy Lab"
description:        "The Happy Lab is a human factors in computer security and privacy reserach group at Arizona State University."
about: 		    "We are a group of researchers interested in learning how to better protect people by first understanding how people interact with software. Currently, our focus "

# URL
url:                http://happyresearchlab.com
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
#  - name:           "about"
#    href:           "/about"
  - name:           "publications"
    href:           "/publication"
#  - name:           "people"
#    href:           "/people"
  # - name:           "blog"
    # href:           "/blog"
#   - name:           "abstracts"
#     href:           "/abstracts"
#  - name:           "lab teachings"
#    href:           "/presentations"
  - name:           "Join the Lab!"
    href:           "/apply"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html


# Publications

## WEI_USENIX_24
wei_usenix_24_pdf: https://jaronm.ink/assets/pdf/papers/sociodemographic-solk_usenix24.pdf


## MINK_CHI_24
mink_chi_24_pdf: https://jaronm.ink/assets/pdf/papers/deepfake-moderation-mistakes_chi24.pdf
mink_chi_24_talk: https://drive.google.com/file/d/1tn3Xx-y8hn4SirornvA_lxoV66BbgFk9/view?usp=sharing

## MINK_USENIX_23

mink_usenix_23_pdf: https://jaronm.ink/assets/pdf/papers/security-is-not-my-field_usenix23.pdf
mink_usenix_23_slides: https://www.usenix.org/system/files/sec23_slides_mink.pdf
mink_usenix_23_talk: https://www.youtube.com/watch?v=a9meMcS79pM


## INAM_IEEE_23
inam_ieee_23_pdf: https://jaronm.ink/assets/pdf/papers/history-is-a-vast-warning-system_ieee-23.pdf

## MINK_IEEE_23
mink_ieee_23_pdf: https://jaronm.ink/assets/pdf/papers/everybodys-got-ml_ieee23.pdf
mink_ieee_23_teaser: https://drive.google.com/file/d/1pYXwHbTudrwZ-MxGuEBnykbUK4Su0bGz/view?usp=share_link
mink_ieee_23_slides: https://jaronm.ink/assets/pdf/presentation/everybodys-got-ml_ieee23_talk.pdf
mink_ieee_23_talk: https://www.youtube.com/watch?v=O6dlZdiJVOQ


## INAM_ACSAC_22
inam_acsac_22_pdf: https://jaronm.ink/assets/pdf/papers/faust_acsac22.pdf


## ZHANG_WWW_22
zhang_www_22_pdf: https://jaronm.ink/assets/pdf/papers/beyond-bot-detection_www22.pdf
zhang_www_22_news_thetransmitter: https://www.thetransmitter.org/ethics/scammers-threaten-quality-of-research-survey-data/

## MINK_USENIX_22
mink_usenix_22_pdf: https://jaronm.ink/assets/pdf/papers/deepphish_usenix22.pdf
deepphish_page: https://jaronm.ink/deepphish/
mink_usenix_22_slides: https://www.usenix.org/system/files/sec22_slides-mink.pdf
mink_usenix_22_supp: https://github.com/JaronMink/DeepPhish
mink_usenix_22_talk: https://www.youtube.com/watch?v=wrRQdcXR-98
news_usenix_22_futurum: https://futurumcareers.com/can-you-trust-what-you-see-online
news_usenix_22_newscientist: https://www.newscientist.com/article/2308977-people-are-bad-at-spotting-fake-linkedin-profiles-generated-by-ai/

## MINK_CHI_22
mink_chi_22_pdf: https://jaronm.ink/assets/pdf/papers/users-can-deduce_chi22.pdf
mink_chi_22_supp: https://bitbucket.org/sts-lab/epz-game-chi22 
mink_chi_22_talk: https://www.youtube.com/watch?v=eGElBs1VrZE
mink_chi_22_slides: https://docs.google.com/presentation/d/1wSqnbfuTtRh-FDq6fE_GYEsEFbU55QKV/edit?usp=sharing&ouid=111263531954489916796&rtpof=true&sd=true
mink_chi_22_news_the21stshow: https://will.illinois.edu/21stshow/story/how-private-is-your-health-tracking-app-data

## Michael20
michael20_pdf: https://jaronm.ink/assets/pdf/papers/forensicvalidity_acsac20.pdf
michael20_talk: https://drive.google.com/file/d/1BZu_9k2i830O2Bzt9uXwZkNP-oBEYRdH/view?usp=sharing
michael20_slides: https://drive.google.com/file/d/1Mmkcrxmp5dYf0Eei3F3-PbE7VgHa1Gp7/view?usp=sharing
